# fly.toml app configuration file generated for white-morning-7557 on 2023-06-10T15:23:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "white-morning-7557"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
